import { Router } from 'express';
import path from 'node:path';
import fs from 'node:fs';
import multer from 'multer';
import crypto from 'node:crypto';
import { env } from '../config/env.js';
import { requireAdmin } from '../middleware/auth.js';
import { asyncHandler, HttpError } from '../utils/http.js';
import * as products from '../controllers/product.controller.js';
import * as settings from '../controllers/settings.controller.js';
import * as coupons from '../controllers/coupon.controller.js';
import * as orders from '../controllers/order.controller.js';
import * as pages from '../controllers/page.controller.js';
import * as contact from '../controllers/contact.controller.js';
import * as customers from '../controllers/customer.controller.js';
import * as media from '../controllers/media.controller.js';

const router=Router(); router.use(requireAdmin);
router.get('/products',asyncHandler(products.adminList));router.post('/products',asyncHandler(products.create));router.put('/products/:id',asyncHandler(products.update));router.delete('/products/:id',asyncHandler(products.remove));
router.put('/settings/store_settings',asyncHandler(settings.putStore));router.put('/settings/home_settings',asyncHandler(settings.putHome));
router.get('/coupons',asyncHandler(coupons.list));router.post('/coupons',asyncHandler(coupons.create));router.put('/coupons/:id',asyncHandler(coupons.update));router.delete('/coupons/:id',asyncHandler(coupons.remove));
router.get('/orders',asyncHandler(orders.adminList));router.get('/orders/:id',asyncHandler(orders.adminOne));router.patch('/orders/:id/status',asyncHandler(orders.status));router.delete('/orders/:id',asyncHandler(orders.remove));
router.get('/customers',asyncHandler(customers.list));
router.get('/pages',asyncHandler(pages.adminList));router.post('/pages',asyncHandler(pages.create));router.put('/pages/:id',asyncHandler(pages.update));router.delete('/pages/:id',asyncHandler(pages.remove));
router.get('/messages',asyncHandler(contact.list));router.patch('/messages/:id',asyncHandler(contact.update));
const uploadPath=path.resolve(env.uploadDir);fs.mkdirSync(uploadPath,{recursive:true});
const upload=multer({storage:multer.diskStorage({destination:uploadPath,filename:(_req,file,cb)=>cb(null,`${Date.now()}-${crypto.randomBytes(4).toString('hex')}${path.extname(file.originalname).toLowerCase()}`)}),limits:{fileSize:5*1024*1024},fileFilter:(_req,file,cb)=>{if(!['image/jpeg','image/png','image/webp','image/gif'].includes(file.mimetype))return cb(new HttpError(400,'Only JPG, PNG, WEBP and GIF images are allowed.'));cb(null,true);}});
router.get('/media',asyncHandler(media.list));router.post('/media',upload.single('image'),asyncHandler(media.uploaded));router.delete('/media/:id',asyncHandler(media.remove));
export default router;
